### ISSUE TITLE
[Issue] TypeError: Cannot read property 'world' of undefined

### ISSUE THREAD

**Issue by Rutes** [Valandur/admin-panel#17]
I clicked the MMCRestrict button in the admin panel...
I don't have a world called "world" - maybe that is the issue?

TypeError: Cannot read property 'world' of undefined

Stacktrace:
    in t
    in t
    in Translate(t)
    in div
    in r
    in t
    in Connect(t)
    in t
    in t
    in Translate(t)
    in Connect(Translate(t))
    in t
    in t
    in t
    in Connect(t)
    in t
    in t
    in t
    in div
    in r
    in div
    in r
    in div
    in t
    in t
    in Translate(t)
    in Connect(Translate(t))
    in t
    in t
    in t
    in t
    in n
    in div
    in t

**Comment by Valandur** [comment]
This is fixed in [v5.0.4](https://github.com/Valandur/admin-panel/releases/tag/v5.0.4)
