### ISSUE TITLE
[Issue] Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20location%2C%20link%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### ISSUE THREAD

**Issue by Jerry996666** [Valandur/admin-panel#2]
<Say a little about what happend>

Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20location%2C%20link%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Stacktrace:
    in td
    in r
    in tr
    in r
    in tbody
    in r
    in table
    in r
    in div
    in t
    in t
    in Translate(t)
    in div
    in r
    in t
    in Connect(t)
    in t
    in t
    in Translate(t)
    in Connect(Translate(t))
    in t
    in t
    in t
    in div
    in r
    in div
    in r
    in div
    in t
    in t
    in Translate(t)
    in Connect(Translate(t))
    in t
    in t
    in t
    in t
    in n
    in div
    in t

**Comment by Valandur** [comment]
This should be fixed in the latest [v5.0.0](https://github.com/Valandur/admin-panel/releases/tag/v5.0.0) release
