### ISSUE TITLE
[Issue] Attempting to edit plugin config causes error

### ISSUE THREAD

**Issue by ThiagoTGM** [Valandur/admin-panel#21]
Upon attempting to edit the configs of one of my plugins through the admin panel (any of them) causes the following error to be thrown, and none of the buttons in the panel work afterward (I have to essentially close and open the panel again for it to work)

TypeError: Cannot set property 'editorRef' of undefined

Stacktrace:
    in div
    in t
    in div
    in t
    in div
    in p
    in div
    in t
    in c
    in div
    in t
    in c
    in t
    in t
    in t
    in t
    in Unknown
    in Connect(Component)
    in n
    in t
    in t
    in div
    in p
    in div
    in p
    in div
    in t
    in Unknown
    in Connect(Component)
    in t
    in t
    in t
    in t
    in t
    in t

**Comment by jmanpenilla** [comment]
Same
