### ISSUE TITLE
[Issue] Tried to edit configs inside of the panel for spongeforge

### ISSUE THREAD

**Issue by Piehthyte** [Valandur/admin-panel#22]
<Say a little about what happened>

TypeError: Cannot set property 'editorRef' of undefined

Stacktrace:
    in div
    in t
    in div
    in t
    in div
    in p
    in div
    in t
    in c
    in div
    in t
    in c
    in t
    in t
    in t
    in t
    in Unknown
    in Connect(Component)
    in n
    in t
    in t
    in div
    in p
    in div
    in p
    in div
    in t
    in Unknown
    in Connect(Component)
    in t
    in t
    in t
    in t
    in t
    in t

**Comment by Valandur** [comment]
Duplicate of #21
