### ISSUE TITLE
[Issue] Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bid%2C%20name%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### ISSUE THREAD

**Issue by FlamingArmor** [Valandur/admin-panel#3]
<Say a little about what happend>
I was on the map, I clicked on the yellow player dot for myself which brought up a tooltip. I got pumped when I saw the destroy button. I did not want to destroy myself however, I instead clicked a green entity an inch over and it threw an error

Edit: I should mention there are several non-vanilla creatures, including MoCreatures walkin around

Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bid%2C%20name%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Stacktrace:
    in div
    in r
    in div
    in r
    in div
    in div
    in div
    in r
    in e
    in Connect(e)
    in t
    in t
    in t
    in div
    in r
    in div
    in r
    in div
    in t
    in t
    in Translate(t)
    in Connect(Translate(t))
    in t
    in t
    in t
    in t
    in n
    in div
    in t

**Comment by Valandur** [comment]
This should be fixed in the latest [v5.0.0](https://github.com/Valandur/admin-panel/releases/tag/v5.0.0) release
