### ISSUE TITLE
[Issue] Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bid%2C%20name%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### ISSUE THREAD

**Issue by CanExiOne** [Valandur/admin-panel#6]
<I was watching map in "map" tab :|>

Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bid%2C%20name%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Stacktrace:
    in div
    in r
    in div
    in r
    in div
    in div
    in div
    in r
    in e
    in Connect(e)
    in t
    in t
    in t
    in div
    in r
    in div
    in r
    in div
    in t
    in t
    in Translate(t)
    in Connect(Translate(t))
    in t
    in t
    in t
    in t
    in n
    in div
    in t

**Comment by Valandur** [comment]
This should be fixed in the latest [v5.0.0](https://github.com/Valandur/admin-panel/releases/tag/v5.0.0) release
